# Generated by Django 3.2.15 on 2024-02-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('APPLICANT', 'Applicant'), ('RH', 'RH'), ('COMPANY', 'Company')], max_length=15, verbose_name='Roles'),
        ),
    ]
