# Generated by Django 3.2.15 on 2024-02-09 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(verbose_name='Applicant skills')),
                ('status_of_searching', models.CharField(choices=[('ACTIVE_SEARCH', 'Active search'), ('IN_CONSIDERATION', 'In consideration'), ('BUSY', 'Busy')], max_length=20, verbose_name='Status of searching')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company name')),
                ('description', models.TextField(verbose_name='Company description')),
                ('num_of_employees', models.IntegerField(verbose_name='Number of employees')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='RH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.TextField(verbose_name='RH services')),
                ('price', models.IntegerField(verbose_name='Price for service')),
            ],
            options={
                'verbose_name': 'RH',
                'verbose_name_plural': 'RHs',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title of vacancy')),
                ('description', models.TextField(verbose_name='Description of vacancy')),
                ('salary', models.IntegerField(verbose_name='Salary per month')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh_kosmos.company', verbose_name='Company vacancy')),
            ],
        ),
    ]
