# Generated by Django 3.2.15 on 2024-02-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh_kosmos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
