# Generated by Django 3.2.15 on 2024-02-09 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rh_kosmos', '0003_alter_vacancy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='company/', verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
