# Generated by Django 3.2.15 on 2024-02-09 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rh_kosmos', '0004_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rh',
            name='subscription',
            field=models.BooleanField(verbose_name='Subscription'),
            preserve_default=False,
        ),
    ]
