# Generated by Django 3.2.15 on 2024-02-09 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_reviews_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='Post photo'),
            preserve_default=False,
        ),
    ]
